name: mobile_nhom17_2021
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  email_validator: '^1.0.6' # Hình như GetUtil đã có
  flutter_svg: ^0.22.0 # Icon svg
  carousel_pro: ^1.0.0 # Carousel
  http: ^0.13.3 # tương tác với api, websocket
  json_annotation: ^3.0.1 # @Serializable
  provider: ^5.0.0 # Quản lý state dạng kế thừa
  intl: ^0.17.0 # Định dạng số, ngày giờ ,...
  flutter_search_panel: ^1.0.1
  persistent_bottom_nav_bar: ^4.0.2 # Bottom Navigation bar tạo sẵn
  shared_preferences: ^2.0.6
  fluttertoast: ^8.0.7
  flash: ^2.0.0
  flutter_spinkit: ^5.0.0
  bubble_tab_indicator: ^0.1.6
  # google_fonts: ^2.1.0
  shimmer: ^2.0.0 # Tạo hiệu ứng bóng
  # flutter_typeahead: ^3.1.3 #auto compple in search form
  timeago: ^3.0.2
  charts_flutter: ^0.10.0
  badges: ^2.0.1 # cái số trên giỏ hàng 
  # google_maps_flutter: ^2.0.6
  get: ^4.1.4 # GetXXXXXXXXXXXXXXXXXXX
  dio: ^4.0.0 # 
  get_storage: ^2.0.2 # Lưu data dạng key-value
  flutter_local_notifications: ^6.0.0 # Hiển thị. lập lịch thông báo
  flutter_native_timezone: ^2.0.0 # Múi giờ, time cho local notification
  firebase_messaging: ^10.0.2 # Nhận thông báo, lập lịch từ firebase
  firebase_core: ^1.3.0 # Firebase
  url_launcher: ^6.0.7 # Điều hướng tới url, phone, email hay message
  webview_flutter: ^2.0.9 # Trang web trong app
  connectivity_plus: ^1.0.4 # Kiểm tra kết nối wifi của thiết bị
  flutter_slidable: ^0.6.0 # Slide cho list item (can be dissmissed)
  fl_chart: ^0.36.2 # chart
  flutter_rating_bar: ^4.0.0 # Thanh đánh giá sản phẩm
  percent_indicator: ^3.0.1 # Thanh phần trăm
  image_picker: ^0.8.1+3 # Lấy hình ảnh từ camera hoặc image library
  firebase_storage: ^9.0.0 # upload download file từ firebase
  firebase_analytics: ^8.1.2
  cloud_firestore: ^2.3.0
  permission_handler: ^8.1.2 # Xin quyền trên điện thoại
  # flutter_signin_button: ^2.0.0
  sign_button: ^2.0.0
  firebase_auth: ^2.0.0
  google_sign_in: ^5.0.4
  font_awesome_flutter: ^9.1.0
  # flutter_native_splash: ^1.2.0
  html_editor_enhanced: ^2.1.0
  flutter_colorpicker: ^0.4.0
  direct_select_flutter: ^1.1.1
  transparent_image: ^2.0.0
  carousel_slider: ^4.0.0
  video_player: ^2.1.10
  youtube_player_flutter: ^8.0.0


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^3.3.0 # Serializeble
  build_runner: ^1.0.0 # Generate code
  flutter_launcher_icons: ^0.9.0

flutter_icons:
  android: "launcher_icon"
  image_path: "assets/logo.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - assets/videos/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: RobotoMono
      fonts:
        - asset: assets/fonts/RobotoMono-VariableFont_wght.ttf
        - asset: assets/fonts/RobotoMono-Italic-VariableFont_wght.ttf
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-ExtraLight.ttf
    - family: Karla
      fonts:
        - asset: assets/fonts/Karla-Light.ttf

  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
