import 'package:get/get.dart';

class Translates extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          'price': "Price",
          'shop-now': 'Shop now',
          'home': 'Home',
          'menu': 'Menu',
          'shop': 'Shop',
          'shop-all': 'Shop all',
          'new': 'New',
          'hot': 'Hot',
          'highlight': 'Highlight',
          'category': 'Category',
          'brand': 'Brand',
          'collection': 'Collection',
          'men': "Men",
          'woman': 'Woman',
          'children': "Children",
          'whishlist': 'whishlist',
          'account': 'Account',
          'address': 'Address',
          'edit': 'Edit',
          'change-pw': 'Change password',
          'change': 'Change',
          'view': 'View',
          'orders': 'Orders',
          'sign-out': 'Sign out',
          'login': 'Login',
          'register': 'Register',
          'forgot-pw': 'Forgot password',
          'discount': 'Discount',
          'see-more': 'See more',
          'buy-now': 'Buy now',
          'product': 'product',
          'contact': 'contact',
          'login-info': 'Infomation',
          'or': 'or',
          'all': 'All product',
          'quick-buy': "Quick buy",
          'checkout': "Checkout",
          'total-price': 'Total price',
          'rest': 'Rest',
          'email-address': "Email address",
          'password': "Password",
          'fetch': 'Fetch data',
        },
        'vi': {
          'price': "Giá",
          'shop-now': 'Cửa hàng',
          'home': 'Trang chủ',
          'menu': 'Danh mục',
          'shop-all': 'Shop all',
          'new': 'Mới nhất',
          'hot': 'Bán chạy',
          'highlight': 'Nổi bật',
          'category': 'Loại sản phẩm',
          'brand': 'Thương hiệu',
          'collection': 'Bộ sưu tập',
          'men': "Nam",
          'woman': 'Nữ',
          'children': "Trẻ em",
          'shop': 'Cửa hàng',
          'whishlist': 'Yêu thích',
          'account': 'Tài khoản',
          'address': 'Địa chỉ',
          'edit': 'Chỉnh sửa',
          'change-pw': 'Thay đổi mật khẩu',
          'change': 'Thay đổi',
          'view': 'Xem',
          'orders': 'Quản lý đơn hàng',
          'sign-out': 'Đăng xuất',
          'login': 'Đăng nhập',
          'register': 'Đăng ký',
          'forgot-pw': 'Quên mật khẩu',
          'discount': 'Giảm giá',
          'see-more': 'Xem thêm',
          'buy-now': 'Mua ngay',
          'product': 'Sản phẩm',
          'contact': 'Liên lạc',
          'login-info': 'Thông tin đăng nhập',
          'or': 'hoặc',
          'all': 'Tất cả',
          'quick-buy': "Mua nhanh",
          'checkout': "Thanh toán",
          'total-price': 'Tổng giá',
          'rest': 'Còn lại',
          'email-address': "Địa chỉ email",
          'password': "Mật khẩu",
          'fetch': 'Lấy dữ liệu',
        }
      };
}
